name: Android Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android-tests:
    runs-on: ubuntu-latest

    services:
      appium:
        image: appium/appium:latest
        ports:
          - 4723:4723
        options: >-
          --health-cmd="curl -f http://localhost:4723/wd/hub/status || exit 1"
          --health-interval=15s
          --health-timeout=10s
          --health-retries=10
        env:
          APPIUM_RELAXED_SECURITY: 'true'
          APPIUM_BASE_PATH: '/wd/hub'

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          target: default
          channel: stable

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: Nexus 6
          disable-animations: true

      - name: Wait for Android Emulator to boot
        run: adb wait-for-device

      - name: Inspect Appium container logs
        run: docker logs $(docker ps -q --filter "ancestor=appium/appium:latest")

      - name: Run Tests
        env:
          APPIUM_HOST: 'localhost'
          APPIUM_PORT: 4723
          BRAND: gfa
        run: |
          yarn wdio
